apiVersion: v1
kind: Service
metadata:
  name: test-automation-toolkit-service
  namespace: projeto-vr
spec:
  selector:
    app: test-automation-toolkit
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer